exports.seed = function (knex) {
  return knex('developersProjects').insert([
    { id: 1, developer_id: 1, project_id: 1 },
    { id: 2, developer_id: 1, project_id: 2 },
    { id: 3, developer_id: 1, project_id: 3 },
    { id: 4, developer_id: 1, project_id: 4 },
    { id: 5, developer_id: 2, project_id: 5 },
    { id: 6, developer_id: 2, project_id: 6 },
    { id: 7, developer_id: 2, project_id: 7 },
    { id: 8, developer_id: 3, project_id: 8 },
    { id: 9, developer_id: 3, project_id: 9 },
    { id: 10, developer_id: 4, project_id: 10 },
    { id: 11, developer_id: 4, project_id: 11 },
    { id: 12, developer_id: 4, project_id: 12 },
    { id: 13, developer_id: 4, project_id: 13 },
    { id: 14, developer_id: 5, project_id: 14 },
    { id: 15, developer_id: 5, project_id: 15 },
    { id: 16, developer_id: 6, project_id: 16 },
    { id: 17, developer_id: 6, project_id: 17 },
    { id: 18, developer_id: 6, project_id: 18 },
    { id: 19, developer_id: 6, project_id: 19 },
    { id: 20, developer_id: 6, project_id: 20 },
    { id: 21, developer_id: 6, project_id: 21 },
    { id: 22, developer_id: 7, project_id: 22 },
    { id: 23, developer_id: 8, project_id: 23 },
    { id: 24, developer_id: 8, project_id: 24 },
    { id: 25, developer_id: 9, project_id: 25 },
    { id: 26, developer_id: 9, project_id: 26 },
    { id: 27, developer_id: 9, project_id: 27 },
    { id: 28, developer_id: 9, project_id: 28 },
    { id: 29, developer_id: 9, project_id: 29 },
    { id: 30, developer_id: 9, project_id: 30 },
    { id: 31, developer_id: 9, project_id: 31 },
    { id: 32, developer_id: 9, project_id: 32 },
    { id: 33, developer_id: 10, project_id: 33 },
    { id: 34, developer_id: 10, project_id: 34 },
    { id: 35, developer_id: 10, project_id: 35 },
    { id: 36, developer_id: 10, project_id: 36 },
    { id: 37, developer_id: 10, project_id: 37 },
    { id: 38, developer_id: 10, project_id: 38 },
    { id: 39, developer_id: 1, project_id: 39 },
    { id: 40, developer_id: 1, project_id: 40 }
  ])
}
